/*
 * CreateProductJPanel.java
 *
 */
package ui.supplier;

import model.Product;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Feature;
import model.ProductCatalog;
import model.Supplier;

/**
 *
 * @author Yashwanth
 */
public class ViewProductDetailJPanel extends javax.swing.JPanel {

    JPanel workArea;
    Product product;
    Supplier supplier;

    /**
     * Creates new form CreateProductJPanel
     */
    public ViewProductDetailJPanel(JPanel workArea, Product product, Supplier supplier) {
        initComponents();
        this.workArea = workArea;
        this.product = product;
        this.supplier = supplier;

        txtName.setText(this.product.getName());
        txtId.setText(String.valueOf(this.product.getId()));
        txtPrice.setText(String.valueOf(this.product.getPrice()));

        if(this.product.getLogoImage() != null) imgLogo.setIcon(this.product.getLogoImage());
        else imgLogo.setText("No Logo");
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeatures = new javax.swing.JTable();
        btnAddFeature = new javax.swing.JButton();
        btnRemoveFeature = new javax.swing.JButton();
        importLabl = new javax.swing.JLabel();
        importBtn = new javax.swing.JButton();
        importProductLbl = new javax.swing.JLabel();
        importTxtField = new javax.swing.JTextField();
        imgLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblTitle.setText("View Product Details");
        add(lblTitle);
        lblTitle.setBounds(148, 24, 121, 17);

        lblName.setText("Product Name:");
        add(lblName);
        lblName.setBounds(30, 73, 87, 17);

        txtName.setEditable(false);
        add(txtName);
        txtName.setBounds(135, 70, 159, 23);

        lblPrice.setText("Price:");
        add(lblPrice);
        lblPrice.setBounds(523, 73, 33, 17);

        txtPrice.setEditable(false);
        add(txtPrice);
        txtPrice.setBounds(574, 70, 102, 23);

        btnUpdate.setText("Update Product");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(419, 288, 122, 23);

        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1);
        backButton1.setBounds(30, 21, 80, 23);

        txtId.setEditable(false);
        add(txtId);
        txtId.setBounds(346, 70, 159, 23);

        lblId.setText("ID:");
        add(lblId);
        lblId.setBounds(312, 73, 16, 17);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(559, 288, 122, 23);

        tblFeatures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Feature Name", "Value"
            }
        ));
        tblFeatures.setEnabled(false);
        jScrollPane1.setViewportView(tblFeatures);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 111, 651, 159);

        btnAddFeature.setText("Add Feature");
        btnAddFeature.setEnabled(false);
        btnAddFeature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFeatureActionPerformed(evt);
            }
        });
        add(btnAddFeature);
        btnAddFeature.setBounds(30, 288, 101, 23);

        btnRemoveFeature.setText("Remove Feature");
        btnRemoveFeature.setEnabled(false);
        btnRemoveFeature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFeatureActionPerformed(evt);
            }
        });
        add(btnRemoveFeature);
        btnRemoveFeature.setBounds(149, 288, 125, 23);

        importLabl.setText("Import Features");
        add(importLabl);
        importLabl.setBounds(520, 350, 100, 17);

        importBtn.setText("Import");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });
        add(importBtn);
        importBtn.setBounds(520, 410, 72, 23);

        importProductLbl.setText("Product ID");
        add(importProductLbl);
        importProductLbl.setBounds(450, 380, 80, 17);
        add(importTxtField);
        importTxtField.setBounds(600, 380, 130, 23);

        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(imgLogo);
        imgLogo.setBounds(240, 360, 160, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtName.setEditable(true);
        txtPrice.setEditable(true);
        btnSave.setEnabled(true);
        tblFeatures.setEnabled(true);
        btnAddFeature.setEnabled(true);
        btnRemoveFeature.setEnabled(true);

}//GEN-LAST:event_btnUpdateActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void backAction() {

        workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageProductCatalogJPanel manageProductCatalogJPanel = (ManageProductCatalogJPanel) component;
        manageProductCatalogJPanel.refreshTable();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        product.setPrice(Integer.parseInt(txtPrice.getText()));
        product.setName(txtName.getText());
        saveFeatures();
        
        txtName.setEditable(false);
        txtPrice.setEditable(false);
        btnSave.setEnabled(false);
        tblFeatures.setEnabled(false);
        btnAddFeature.setEnabled(false);
        btnRemoveFeature.setEnabled(false);
        
        JOptionPane.showMessageDialog(this, "Product information saved","Information",JOptionPane.INFORMATION_MESSAGE);
        refreshTable();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void saveFeatures() {
        
        DefaultTableModel model = (DefaultTableModel) tblFeatures.getModel();
        
        for(int i=0; i< model.getRowCount(); i++){
            Feature currentFeature = product.getFeatures().get(i);
            currentFeature.setName(tblFeatures.getValueAt(i, 0).toString());
            currentFeature.setValue(tblFeatures.getValueAt(i, 1));

        }
       
    }

    private void btnAddFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFeatureActionPerformed
        // TODO add your handling code here:
        Feature newFeature = product.addNewFeature(product);
        newFeature.setName("New Feature");
        newFeature.setValue("Type Value here");
        
        saveFeatures();
        
        refreshTable();
        
       
    }//GEN-LAST:event_btnAddFeatureActionPerformed

    private void btnRemoveFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFeatureActionPerformed
        // TODO add your handling code here:
        saveFeatures();
        
        int row = tblFeatures.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        product.getFeatures().remove(row);
        refreshTable();
        

       
    }//GEN-LAST:event_btnRemoveFeatureActionPerformed

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        // TODO add your handling code here:
        int productId = Integer.parseInt(importTxtField.getText());

        ProductCatalog list = this.supplier.getProductCatalog();
        Product product = list.searchProduct(productId);
        ArrayList<Feature> features = product.getFeatures();

        this.product.setFeatures(features);
        
        saveFeatures();
        refreshTable();
        
    }//GEN-LAST:event_importBtnActionPerformed

    public void refreshTable() {

       DefaultTableModel model = (DefaultTableModel) tblFeatures.getModel();
       model.setRowCount(0);
       
       for(Feature f : product.getFeatures()){
           Object row[] = new Object[2];
           row[0] = f;
           row[1] = f.getValue() == null ? "Empty" : f.getValue().toString();
           model.addRow(row);
       }    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JButton btnAddFeature;
    private javax.swing.JButton btnRemoveFeature;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton importBtn;
    private javax.swing.JLabel importLabl;
    private javax.swing.JLabel importProductLbl;
    private javax.swing.JTextField importTxtField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblFeatures;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
