/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import business.Account;
import business.AccountDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author yash
 */


public class CreateAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountJPanel
     */

    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    
    CreateAccountJPanel(JPanel userProcessContainer, AccountDirectory accountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.accountDirectory = accountDirectory;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        routingNoLbl = new javax.swing.JLabel();
        accNoLbl = new javax.swing.JLabel();
        bankNameLbl = new javax.swing.JLabel();
        balanceLbl = new javax.swing.JLabel();
        routingNoTxtField = new javax.swing.JTextField();
        accNoTxtField = new javax.swing.JTextField();
        bankNameTxtField = new javax.swing.JTextField();
        balanceTxtField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Account");
        jLabel1.setOpaque(true);

        routingNoLbl.setText("Routing Number");

        accNoLbl.setText("Account Number");

        bankNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankNameLbl.setText("Bank Name");

        balanceLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceLbl.setText("Balance");

        routingNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routingNoTxtFieldActionPerformed(evt);
            }
        });

        accNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoTxtFieldActionPerformed(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(314, 314, 314)
                            .addComponent(createBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(228, 228, 228)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(routingNoLbl)
                                .addComponent(accNoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bankNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(balanceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(routingNoTxtField)
                                .addComponent(accNoTxtField)
                                .addComponent(bankNameTxtField)
                                .addComponent(balanceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(backBtn))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routingNoLbl)
                    .addComponent(routingNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNoLbl)
                    .addComponent(accNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameLbl)
                    .addComponent(bankNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLbl)
                    .addComponent(balanceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(createBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoTxtFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        
        routingNoTxtField.setBorder(null);
        accNoTxtField.setBorder(null);
        bankNameTxtField.setBorder(null);
        balanceTxtField.setBorder(null);

        String routingNumber = routingNoTxtField.getText();
        String accountNumber = accNoTxtField.getText();
        String bankName = bankNameTxtField.getText();
        
        if(routingNumber.matches(".*[a-zA-Z]+.*")){
            Border customBorder = new LineBorder(Color.RED, 2);
            routingNoTxtField.setBorder(customBorder);
            JOptionPane.showMessageDialog(this, "Please rectify the errors in the highlighted fields!");
            return;
        }
        
                
        if(accountNumber.matches(".*[a-zA-Z]+.*")){
            Border customBorder = new LineBorder(Color.RED, 2);
            accNoTxtField.setBorder(customBorder);
            JOptionPane.showMessageDialog(this, "Please rectify the errors in the highlighted fields!");
            return;
        }
        
        if(balanceTxtField.getText().matches(".*[a-zA-Z]+.*")){
            Border customBorder = new LineBorder(Color.RED, 2);
            balanceTxtField.setBorder(customBorder);
            JOptionPane.showMessageDialog(this, "Please rectify the errors in the highlighted fields!");
            return;
        }
        
        if(bankName.matches(".*\\d+.*")){
            Border customBorder = new LineBorder(Color.RED, 2);
            bankNameTxtField.setBorder(customBorder);
            JOptionPane.showMessageDialog(this, "Please rectify the errors in the highlighted fields!");
            return;
        }
        
        if(routingNumber.isBlank() || accountNumber.isBlank() || bankName.isBlank() || balanceTxtField.getText().isBlank()){
             JOptionPane.showMessageDialog(this, "Fields are empty!");
             return;
        }
        
        Account account = accountDirectory.addAccount();

        account.setAccountNumber(accountNumber);
        account.setBalance(Integer.parseInt(balanceTxtField.getText()));
        account.setBankName(bankName);
        account.setRoutingNumber(routingNumber);
        
        JOptionPane.showMessageDialog(this, "Account Successfully created!");
    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer .getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void routingNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routingNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routingNoTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accNoLbl;
    private javax.swing.JTextField accNoTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel balanceLbl;
    private javax.swing.JTextField balanceTxtField;
    private javax.swing.JLabel bankNameLbl;
    private javax.swing.JTextField bankNameTxtField;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel routingNoLbl;
    private javax.swing.JTextField routingNoTxtField;
    // End of variables declaration//GEN-END:variables
}
