/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import business.Account;
import business.AccountDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author yash
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */

     private JPanel userProcessContainer;
     private Account account;
    ViewAccountJPanel(JPanel userProcessContainer, Account acc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = acc;
        populateAccountDetails();
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
        
    }

    private void populateAccountDetails(){
        accNoTxtField.setText(account.getAccountNumber());
        bankNameTxtField.setText(account.getBankName());
        routingNoTxtField.setText(account.getRoutingNumber());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        routingNoTxtField = new javax.swing.JTextField();
        accNoTxtField = new javax.swing.JTextField();
        bankNameTxtField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        routingNoLbl = new javax.swing.JLabel();
        accNoLbl = new javax.swing.JLabel();
        bankNameLbl = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();

        routingNoTxtField.setEnabled(false);
        routingNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routingNoTxtFieldActionPerformed(evt);
            }
        });

        accNoTxtField.setEnabled(false);
        accNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoTxtFieldActionPerformed(evt);
            }
        });

        bankNameTxtField.setEnabled(false);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Account");
        jLabel1.setOpaque(true);

        routingNoLbl.setText("Routing Number");

        accNoLbl.setText("Account Number");

        bankNameLbl.setText("Bank Name");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(228, 228, 228)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(routingNoLbl)
                                .addComponent(accNoLbl)
                                .addComponent(bankNameLbl)
                                .addComponent(saveBtn))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(routingNoTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(accNoTxtField)
                                .addComponent(bankNameTxtField)
                                .addComponent(updateBtn)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(backBtn))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routingNoLbl)
                    .addComponent(routingNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNoLbl)
                    .addComponent(accNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameLbl)
                    .addComponent(bankNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn))
                .addGap(70, 70, 70)
                .addComponent(backBtn)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoTxtFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String routingNumber = routingNoTxtField.getText();
        String accountNumber = accNoTxtField.getText();
        String bankName = bankNameTxtField.getText();
        
        routingNoTxtField.setBorder(null);
        accNoTxtField.setBorder(null);
        bankNameTxtField.setBorder(null);
        
        if(routingNumber.matches(".*[a-zA-Z]+.*")){
            Border customBorder = new LineBorder(Color.RED, 2);
            routingNoTxtField.setBorder(customBorder);
            JOptionPane.showMessageDialog(this, "Please rectify the errors in the highlighted fields!");
            return;
        }
        
                
        if(accountNumber.matches(".*[a-zA-Z]+.*")){
            Border customBorder = new LineBorder(Color.RED, 2);
            accNoTxtField.setBorder(customBorder);
            JOptionPane.showMessageDialog(this, "Please rectify the errors in the highlighted fields!");
            return;
        }

        
        if(bankName.matches(".*\\d+.*")){
            Border customBorder = new LineBorder(Color.RED, 2);
            bankNameTxtField.setBorder(customBorder);
            JOptionPane.showMessageDialog(this, "Please rectify the errors in the highlighted fields!");
            return;
        }
        
        if(routingNumber.isBlank() || accountNumber.isBlank() || bankName.isBlank()){
             JOptionPane.showMessageDialog(this, "Fields are empty!");
            return;
        }
        
        account.setAccountNumber(accountNumber);
        account.setBankName(bankName);
        account.setRoutingNumber(routingNumber);

        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
        
        routingNoTxtField.setEnabled(false);
        accNoTxtField.setEnabled(false);
        bankNameTxtField.setEnabled(false);
        
        JOptionPane.showMessageDialog(this, "Account updated successfully!");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        Component component = userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 1);
        if(component instanceof ManageAccountJPanel manageAccountPanel) {
            manageAccountPanel.populateTable();
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        routingNoTxtField.setEnabled(true);
        accNoTxtField.setEnabled(true);
        bankNameTxtField.setEnabled(true);
        saveBtn.setEnabled(true);
        updateBtn.setEnabled(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void routingNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routingNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routingNoTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accNoLbl;
    private javax.swing.JTextField accNoTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bankNameLbl;
    private javax.swing.JTextField bankNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel routingNoLbl;
    private javax.swing.JTextField routingNoTxtField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
